name: Kernel Builder

on:
  workflow_dispatch:
    inputs:
      kernel_url:
        description: Kernel GitHub URL
        required: true
        default: https://github.com/Kenshin1444/NekoPoi-Kranul-B.git

      kernel_branch:
        description: Kernel branch
        required: true
        default: main

jobs:
  Build-Kernel:
    runs-on: ubuntu-24.04

    env:
      KERNEL_NAME: courbet
      KERNEL_DIR: kernel
      ARCH: arm64
      SUBARCH: arm64
      ANYKERNEL_DIR: AnyKernel3

      KBUILD_BUILD_USER: Giyokun07
      KBUILD_BUILD_HOST: github

      TG_TOKEN: 8647652050:AAG0ZKtMuE4NhlOKx8EHz4VHfgPLlguMTqw
      TG_CHAT_ID: 7540957411

    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
        bc bison build-essential curl flex git \
        libssl-dev libncurses-dev lzop \
        python3 unzip wget xz-utils zip

    - name: Clone Kernel
      run: |
        git clone --depth=1 \
        ${{ github.event.inputs.kernel_url }} \
        -b ${{ github.event.inputs.kernel_branch }} \
        $KERNEL_DIR

    - name: Clone Clang
      run: |
        git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r547379.git \
        --depth=1 -b 15.0 clang

    - name: Download Eva GCC
      run: |
        mkdir gcc
        cd gcc

        ASSET_URLS=$(curl -s https://api.github.com/repos/mvaisakh/gcc-build/releases/latest \
        | grep browser_download_url | cut -d '"' -f 4 | grep ".xz")

        for url in $ASSET_URLS; do
          wget -q $url
        done

        for file in *.xz; do
          tar -xf $file
        done

        echo "GCC64_DIR=$(pwd)/$(ls | grep aarch64 | head -n1)" >> $GITHUB_ENV
        echo "GCC32_DIR=$(pwd)/$(ls | grep arm | head -n1)" >> $GITHUB_ENV

    - name: Build Kernel
      run: |
        export PATH=$PWD/clang/bin:$GCC64_DIR/bin:$GCC32_DIR/bin:$PATH

        cd $KERNEL_DIR
        mkdir out

        make O=out ARCH=arm64 ${KERNEL_NAME}_defconfig

        make -j$(nproc) \
        O=out \
        ARCH=arm64 \
        LLVM=1 \
        LLVM_IAS=1 \
        CROSS_COMPILE=$GCC64_DIR/bin/aarch64-elf- \
        CROSS_COMPILE_COMPAT=$GCC32_DIR/bin/arm-eabi-

    - name: Clone AnyKernel3
      run: |
        git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git

    - name: Repack AnyKernel3
      run: |
        cp $KERNEL_DIR/out/arch/arm64/boot/Image AnyKernel3/

        cd AnyKernel3

        zip -r9 ../${{ env.KERNEL_NAME }}-Kernel.zip * -x .git README.md

    - name: Upload to Telegram
      run: |
        curl -F document=@${{ env.KERNEL_NAME }}-Kernel.zip \
        -F caption="✅ Kernel Build Success
Device: courbet
Repo: NekoPoi-Kranul-B
Commit: $GITHUB_SHA" \
        https://api.telegram.org/bot$TG_TOKEN/sendDocument?chat_id=$TG_CHAT_ID
